owner: sctech-tr
repo: status
sites:
  - name: sctech.mooo.com - mirror 1
    url: https://sctech.mooo.com
  - name: sctech.pages.gay - mirror 2
    url: https://sctech.pages.gay
  - name: sctech link shortener
    url: https://go.sctech.mooo.com
  - name: this website
    url: https://status.sctech.mooo.com
  - name: osearch
    url: https://search.sctech.mooo.com
  - name: lwytui
    url: https://lwytui.github.io
  - name: openprofile
    url: https://openprofile.us.to
  - name: about openprofile
    url: http://about.openprofile.us.to
  - name: wwwterminal
    url: https://wwwterminal.h4ck.me
assignees:
  - sctech-tr
status-website:
  theme: night
  cname: status.sctech.mooo.com
  logoUrl: https://raw.githubusercontent.com/sctech-tr/sctech-tr.github.io/main/img/me.jpg
  name: sctech status page
  introTitle: "hi this is the status page for openprofile, wwwterminal and more"
  introMessage: contains status data for: sctech-tr, lwytui, openprofile, wwwterminal
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://sctech.mooo.com
    - title: GitHub
      href: https://github.com/sctech-tr/status
