owner: sctech-tr
repo: status
sites:
  - name: sctech.mooo.com - mirror 1
    url: https://sctech.mooo.com
  - name: sctech.pages.gay - mirror 2
    url: https://sctech.pages.gay
  - name: sctech.netlify.app - mirror 3
    url: https://sctech.netlify.app
  - name: sctech link shortener
    url: https://go.sctech.mooo.com
  - name: statuspage
    url: https://status.sctech.mooo.com
  - name: example statuspage
    url: https://sctech.mooo.com/statuspage/
  - name: kanban board demo
    url: https://kanban-demo-iauy.onrender.com
  - name: osearch
    url: https://search.sctech.mooo.com
  - name: lwytui
    url: https://lwytui.github.io
  - name: openprofile
    url: https://openprofile.us.to
  - name: about openprofile
    url: http://about.openprofile.us.to
  - name: wwwterminal
    url: https://wwwterminal.h4ck.me
  - name: rmsh website
    url: https://remote-shell.github.io
  - name: note and flush website
    url: https://noteflush.github.io
  - name: ‌
    url: https://pinariko.github.io
  - name: lolchat
    url: https://lolch4t.netlify.app
  - name: lolchat backend
    url: https://lolchat-backend.onrender.com
assignees:
  - sctech-tr
status-website:
  theme: night
  cname: status.sctech.mooo.com
  logoUrl: https://raw.githubusercontent.com/sctech-tr/sctech-tr.github.io/main/img/me.jpg
  name: sctech status page
  introTitle: "hi this is the status page for openprofile, lolchat and more"
  introMessage: contains status data for sctech-tr, lwytui, openprofile, wwwterminal, lolchat, rmsh, note+flush
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://sctech.mooo.com
    - title: GitHub
      href: https://github.com/sctech-tr/status
